spring:
   application:
      name: bank
      
   datasource:
      url: jdbc:mysql://localhost:3306/bank
      username: bank
      password: bank
      
   jpa:
      hibernate:
         ddl-auto: update
         dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true 
      defer-datasource-initialization: true
     
   sql:
      init:
         mode: always
         
logging:
   level:
      root: info
      bank: debug
     
        
